import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";

import ConvexClientProvider from "./ConvexClientProvider";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const outfit=Outfit({subsets:['latin'],display:'swap'})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={tr}>
      <body
        className={outfit.className}
      >
        <ConvexClientProvider>
        {children}
        </ConvexClientProvider>
      </body>
    </html>
  );
}
